The Python Standard Library is a comprehensive collection of modules and packages that comes pre-installed with Python, providing a vast range of functionalities to facilitate various programming tasks.

It is designed to be an all-encompassing toolkit, offering built-in solutions for many common needs without requiring additional installations.

Math Module: This library includes modules for math operations, like the math module with functions like sqrt() and constants like pi.

Datetime Module: The datetime module provides classes
like datetime, date, and time for precise date and time manipulation.

os Module: The os module handles file and directory operations like listing files and joining paths.
sys Module: The sys module gives access to system-specific functions and command-line arguments.
json Module: The json module processes JSON data with functions for parsing and encoding.

Pandas: python for data analysis.

Pandas is a powerful and versatile open-source library in Python, specifically designed for data manipulation and analysis.

It provides two primary data structures-DataFrame and Series-that are fundamental for handling structured data efficiently.

Data Frame: The DataFrame is a two-dimensional, size-mutable, and potentially heterogeneous tabular data structure with labeled axes (rows and columns), which allows for easy data manipulation, including merging, reshaping, and aggregating.

Series: The Series, on the other hand, is a one-dimensional labeled array capable of holding any data type, such as integers, floats, or strings, and can be seen as a single column of a DataFrame.

In [2]:
import pandas as pd
sales_data=pd.read_csv('Sales.csv')
sales_data.head() # gives 5 records from the top

,Order_ID,Date,Customer,Product,Category,Region,Salesperson,Quantity,Unit_Price,Discount_Percent,Total_Sales
0,ORD1002,2026-01-09,Customer_02,Smartphone,Electronics,North,Priya,2,35000,15,59500.0
1,ORD1043,2026-01-15,Customer_43,Monitor,Electronics,North,Anjali,5,18000,5,85500.0
2,ORD1045,2026-01-18,Customer_45,Backpack,Accessories,North,Neha,2,2200,5,4180.0
3,ORD1032,2026-01-19,Customer_32,Smartphone,Electronics,South,Vikram,1,35000,10,31500.0
4,ORD1031,2026-01-19,Customer_31,Printer,Electronics,North,Neha,4,16000,0,64000.0

if you have different formate of your file write file formate with read_(file format)

check the shape data types and summary statistics of file

In [ ]:
print("First Few Row of the dataFrame")
print(sales_data.head()) # upper method is better

First Few Row of the dataFrame
  Order_ID        Date     Customer     Product     Category Region  \
0  ORD1002  2026-01-09  Customer_02  Smartphone  Electronics  North
1  ORD1043  2026-01-15  Customer_43     Monitor  Electronics  North
2  ORD1045  2026-01-18  Customer_45    Backpack  Accessories  North
3  ORD1032  2026-01-19  Customer_32  Smartphone  Electronics  South
4  ORD1031  2026-01-19  Customer_31     Printer  Electronics  North

  Salesperson  Quantity  Unit_Price  Discount_Percent  Total_Sales
0       Priya         2       35000                15      59500.0
1      Anjali         5       18000                 5      85500.0
2        Neha         2        2200                 5       4180.0
3      Vikram         1       35000                10      31500.0
4        Neha         4       16000                 0      64000.0

In [ ]:
sales_data.tail() # GIVE THE  last 5 record

,Order_ID,Date,Customer,Product,Category,Region,Salesperson,Quantity,Unit_Price,Discount_Percent,Total_Sales
45,ORD1023,2026-08-04,Customer_23,Backpack,Accessories,South,Rahul,2,2200,10,3960.0
46,ORD1038,2026-08-12,Customer_38,Keyboard,Accessories,North,Sneha,8,2500,5,19000.0
47,ORD1025,2026-08-13,Customer_25,Laptop,Electronics,East,Neha,2,65000,10,117000.0
48,ORD1029,2026-08-19,Customer_29,Office Chair,Furniture,West,Priya,6,12000,15,61200.0
49,ORD1028,2026-08-26,Customer_28,Keyboard,Accessories,South,Vikram,7,2500,5,16625.0

In [ ]:
sales_data.tail(10) #give the last 10 row it is for if you  want an specific rows

,Order_ID,Date,Customer,Product,Category,Region,Salesperson,Quantity,Unit_Price,Discount_Percent,Total_Sales
40,ORD1009,2026-07-17,Customer_09,Smartphone,Electronics,East,Priya,1,35000,5,33250.0
41,ORD1036,2026-07-24,Customer_36,Laptop,Electronics,North,Neha,7,65000,10,409500.0
42,ORD1004,2026-07-27,Customer_04,Monitor,Electronics,North,Rahul,8,18000,10,129600.0
43,ORD1008,2026-08-01,Customer_08,Office Chair,Furniture,East,Neha,2,12000,10,21600.0
44,ORD1013,2026-08-04,Customer_13,Keyboard,Accessories,North,Neha,4,2500,10,9000.0
45,ORD1023,2026-08-04,Customer_23,Backpack,Accessories,South,Rahul,2,2200,10,3960.0
46,ORD1038,2026-08-12,Customer_38,Keyboard,Accessories,North,Sneha,8,2500,5,19000.0
47,ORD1025,2026-08-13,Customer_25,Laptop,Electronics,East,Neha,2,65000,10,117000.0
48,ORD1029,2026-08-19,Customer_29,Office Chair,Furniture,West,Priya,6,12000,15,61200.0
49,ORD1028,2026-08-26,Customer_28,Keyboard,Accessories,South,Vikram,7,2500,5,16625.0

In [ ]:
sales_data.dtypes # give the data types of all column

Order_ID             object
Date                 object
Customer             object
Product              object
Category             object
Region               object
Salesperson          object
Quantity              int64
Unit_Price            int64
Discount_Percent      int64
Total_Sales         float64
dtype: object

In [ ]:
# summary
sales_data.info() # whole summary of data

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order_ID          50 non-null     object
 1   Date              50 non-null     object
 2   Customer          50 non-null     object
 3   Product           50 non-null     object
 4   Category          50 non-null     object
 5   Region            50 non-null     object
 6   Salesperson       50 non-null     object
 7   Quantity          50 non-null     int64
 8   Unit_Price        50 non-null     int64
 9   Discount_Percent  50 non-null     int64
 10  Total_Sales       50 non-null     float64
dtypes: float64(1), int64(3), object(7)
memory usage: 4.4+ KB

In [ ]:
sales_data.describe() # give the statistics in form of numerical column but print only those column which have numerical data

        Quantity    Unit_Price  Discount_Percent    Total_Sales
count  50.000000     50.000000         50.000000      50.000000
mean    4.320000  17600.000000          7.800000   60198.900000
std     2.316225  18693.663665          5.264436   78461.121168
min     1.000000   1200.000000          0.000000    2400.000000
25%     2.000000   2500.000000          5.000000   16625.000000
50%     4.000000  13500.000000         10.000000   38250.000000
75%     6.000000  18000.000000         10.000000   70200.000000
max     8.000000  65000.000000         15.000000  409500.000000

In [ ]:
sales_data.describe(include="all") # include all columns

,Order_ID,Date,Customer,Product,Category,Region,Salesperson,Quantity,Unit_Price,Discount_Percent,Total_Sales
count,50,50,50,50,50,50,50,50.000000,50.000000,50.000000,50.000000
unique,50,46,50,10,3,4,8,NaN,NaN,NaN,NaN
top,ORD1002,2026-01-19,Customer_02,Monitor,Electronics,North,Priya,NaN,NaN,NaN,NaN
freq,1,2,1,7,25,19,13,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.320000,17600.000000,7.800000,60198.900000
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.316225,18693.663665,5.264436,78461.121168
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,1200.000000,0.000000,2400.000000
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.000000,2500.000000,5.000000,16625.000000
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.000000,13500.000000,10.000000,38250.000000
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.000000,18000.000000,10.000000,70200.000000
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.000000,65000.000000,15.000000,409500.000000

In [ ]:
# missing values
sales_data.isnull().sum() # gives all missing vlaue sum function sum all the values of there is null values

Order_ID            0
Date                0
Customer            0
Product             0
Category            0
Region              0
Salesperson         0
Quantity            0
Unit_Price          0
Discount_Percent    0
Total_Sales         0
dtype: int64

In [14]:
print(sales_data['Product'].unique()) # gives all unique value in data frame

['Smartphone' 'Monitor' 'Backpack' 'Printer' 'Laptop' 'Desk'
 'Office Chair' 'Headphones' 'Keyboard' 'Mouse']

In [ ]:
print(sales_data['Region'].value_counts()) # count values

Region
North    19
West     11
East     11
South     9
Name: count, dtype: int64

In [ ]:
print(sales_data.duplicated().sum()) #gives the duplicate row and sum gives how many duplicated rows

0